import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import styles from "@/styles/page.module.scss";

export const metadata: Metadata = {
  title: "Posts Listing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <div className={styles.container}>
          <Navbar />
          <div className={styles.children}>{children}</div>
        </div>
      </body>
    </html>
  );
}
